[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["cd packages/api && npm install"]

[phases.build]
cmds = ["cd packages/api && npm run build"]

[start]
cmd = "cd packages/api && npm start" 