# GIOAT Social Trading Platform - Production Configuration
services:
  - type: web
    name: gioat-platform
    env: node
    buildCommand: cd packages/api && npm ci && NODE_OPTIONS="--max-old-space-size=2048" npm run build
    startCommand: cd packages/api && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 