services:
  - type: web
    name: gioat-platform
    env: node
    buildCommand: cd packages/api && npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: cd packages/api && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 